### ISSUE TITLE
Error: Cannot find module 'moment

### ISSUE THREAD

**Issue by Al0ne-collab** [CodAre-Development/discord.js-guard-bot#1]
`internal/modules/cjs/loader.js:834`
  throw err;
  ^
Error: Cannot find module 'moment'
Require stack:
- /home/al0ne/Masaüstü/bot/bot.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/al0ne/Masaüstü/bot/bot.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/al0ne/Masaüstü/bot/bot.js' ]
}`

**Comment by Furtsy** [comment]
open terminal and write npm i moment
